### PR TITLE
Adding packages which are required if starting from clean distribution

### PR DESCRIPTION
**Pull request by AntonKrug**
Not sure if these websites are autogenerated, but when I tried the installation from clean distribution (Ubuntu/xenial64) I was missing few packages.

### CODE REVIEW

**Comment by ilg-ul** [comment]
that was a problem with the build scripts, which were developed on macOS; those dependencies are not really needed on GNU/Linux.

I recently update the OpenOCD build scripts to fix that dependency

https://github.com/gnu-mcu-eclipse/openocd-build/commit/d9fcb1b0c1c8da35cda86b38afbdb5733138f35d

the other scripts need to be fixed too.

**Comment by AntonKrug** [comment]
Yes, that makes sense, but I think the missing pkg-config was causing issues in autoreconf and showed different problems when ./configure was called.

**Comment by ilg-ul** [comment]
which build script are you using?

when running on GNU/Linux, neither `pkg-config` nor `./configure` should be called in the Docker host, only in the container ; if it does, I would suspect a bug.

**Comment by AntonKrug** [comment]
I'm not sure where exactly it was caused, but I'm using

bash ~/Downloads/openocd-build.git/scripts/build.sh --all

**Comment by ilg-ul** [comment]
this is it. did you update the submodule?

start the script with debug and perhaps you can tell where the problem is.

```bash
$ export DEBUG='-x'
$ bash ~/Downloads/openocd-build.git/scripts/build.sh --all
```

**Comment by AntonKrug** [comment]
==> default: ----------------------------------------------------------------------
==> default:  /usr/bin/mkdir -p '/Host/Work/openocd/install/debian64/include/hidapi'
==> default:  /usr/bin/install -c -m 644 ../hidapi/hidapi.h '/Host/Work/openocd/install/debian64/include/hidapi'
==> default: make[2]: Leaving directory '/tmp/build/debian64/hidapi-hidapi-0.8.0-rc1/linux'
==> default: make[1]: Leaving directory '/tmp/build/debian64/hidapi-hidapi-0.8.0-rc1/linux'
==> default: Making install in libusb
==> default: make[1]: Entering directory '/tmp/build/debian64/hidapi-hidapi-0.8.0-rc1/libusb'
==> default: make[2]: Entering directory '/tmp/build/debian64/hidapi-hidapi-0.8.0-rc1/libusb'
==> default:  /usr/bin/mkdir -p '/Host/Work/openocd/install/debian64/lib'
==> default:  /bin/bash ../libtool   --mode=install /usr/bin/install -c   libhidapi-libusb.la '/Host/Work/openocd/install/debian64/lib'
==> default: libtool: install: /usr/bin/install -c .libs/libhidapi-libusb.so.0.0.0 /Host/Work/openocd/install/debian64/lib/libhidapi-libusb.so.0.0.0
==> default: libtool: install: (cd /Host/Work/openocd/install/debian64/lib && { ln -s -f libhidapi-libusb.so.0.0.0 libhidapi-libusb.so.0 || { rm -f libhidapi-libusb.so.0 && ln -s libhidapi-libusb.so.0.0.0 libhidapi-libusb.so.0; }; })
==> default: libtool: install: (cd /Host/Work/openocd/install/debian64/lib && { ln -s -f libhidapi-libusb.so.0.0.0 libhidapi-libusb.so || { rm -f libhidapi-libusb.so && ln -s libhidapi-libusb.so.0.0.0 libhidapi-libusb.so; }; })
==> default: libtool: install: /usr/bin/install -c .libs/libhidapi-libusb.lai /Host/Work/openocd/install/debian64/lib/libhidapi-libusb.la
==> default: libtool: install: /usr/bin/install -c .libs/libhidapi-libusb.a /Host/Work/openocd/install/debian64/lib/libhidapi-libusb.a
==> default: libtool: install: chmod 644 /Host/Work/openocd/install/debian64/lib/libhidapi-libusb.a
==> default: libtool: install: ranlib /Host/Work/openocd/install/debian64/lib/libhidapi-libusb.a
==> default: libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin" ldconfig -n /Host/Work/openocd/install/debian64/lib
==> default: ----------------------------------------------------------------------
==> default: Libraries have been installed in:
==> default:    /Host/Work/openocd/install/debian64/lib
==> default:
==> default:
==> default: If you ever happen to want to link against installed libraries
==> default: in a given directory, LIBDIR, you must either use libtool, and
==> default:
==> default: specify the full pathname of the library, or use the '-LLIBDIR'
==> default: flag during linking and do at least one of the following:
==> default:    - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
==> default:      during execution
==> default:    - add LIBDIR to the 'LD_RUN_PATH' environment variable
==> default:      during linking
==> default:    - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
==> default:    - have your system administrator add LIBDIR to '/etc/ld.so.conf'
==> default: See any operating system documentation about shared libraries for
==> default: more information, such as the ld(1) and ld.so(8) manual pages.
==> default: ----------------------------------------------------------------------
==> default:  /usr/bin/mkdir -p '/Host/Work/openocd/install/debian64/include/hidapi'
==> default:  /usr/bin/install -c -m 644 ../hidapi/hidapi.h '/Host/Work/openocd/install/debian64/include/hidapi'
==> default: make[2]: Leaving directory '/tmp/build/debian64/hidapi-hidapi-0.8.0-rc1/libusb'
==> default: make[1]: Leaving directory '/tmp/build/debian64/hidapi-hidapi-0.8.0-rc1/libusb'
==> default: Making install in hidtest
==> default: make[1]: Entering directory '/tmp/build/debian64/hidapi-hidapi-0.8.0-rc1/hidtest'
==> default: make[2]: Entering directory '/tmp/build/debian64/hidapi-hidapi-0.8.0-rc1/hidtest'
==> default: make[2]: Nothing to be done for 'install-exec-am'.
==> default:
==> default: make[2]: Nothing to be done for 'install-data-am'.
==> default: make[2]: Leaving directory '/tmp/build/debian64/hidapi-hidapi-0.8.0-rc1/hidtest'
==> default: make[1]: Leaving directory '/tmp/build/debian64/hidapi-hidapi-0.8.0-rc1/hidtest'
==> default: make[1]: Entering directory '/tmp/build/debian64/hidapi-hidapi-0.8.0-rc1'
==> default: make[2]: Entering directory '/tmp/build/debian64/hidapi-hidapi-0.8.0-rc1'
==> default: make[2]: Nothing to be done for 'install-exec-am'.
==> default:  /usr/bin/mkdir -p '/Host/Work/openocd/install/debian64/share/doc/hidapi'
==> default:  /usr/bin/install -c -m 644 README.txt AUTHORS.txt LICENSE-bsd.txt LICENSE-gpl3.txt LICENSE-orig.txt LICENSE.txt '/Host/Work/openocd/install/debian64/share/doc/hidapi'
==> default:  /usr/bin/mkdir -p '/Host/Work/openocd/install/debian64/lib/pkgconfig'
==> default:  /usr/bin/install -c -m 644 pc/hidapi-hidraw.pc pc/hidapi-libusb.pc '/Host/Work/openocd/install/debian64/lib/pkgconfig'
==> default: make[2]: Leaving directory '/tmp/build/debian64/hidapi-hidapi-0.8.0-rc1'
==> default: make[1]: Leaving directory '/tmp/build/debian64/hidapi-hidapi-0.8.0-rc1'
==> default: + touch /tmp/build/debian64/hidapi-hidapi-0.8.0-rc1/stamp-install-completed
==> default: + mkdir -p /tmp/build/debian64/openocd
==> default: + '[' '!' -f /tmp/build/debian64/openocd/config.h ']'
==> default: + echo
==> default:
==> default: + echo 'Running OpenOCD configure...'
==> default: Running OpenOCD configure...
==> default: + '[' debian == win ']'
==> default: + '[' debian == debian ']'
==> default: + LD_LIBRARY_PATH=
==> default: + cd /tmp/build/debian64/openocd
==> default: + tee /Host/Work/openocd/deploy/debian64/configure-output.txt
==> default: + CPPFLAGS='-m64 -pipe'
==> default:
==> default: + LDFLAGS=-Wl,-lpthread
==> default: + PKG_CONFIG_LIBDIR=/Host/Work/openocd/install/debian64/lib/pkgconfig:/Host/Work/openocd/install/debian64/lib64/pkgconfig
==> default: + LD_LIBRARY_PATH=/Host/Work/openocd/install/debian64/lib:/Host/Work/openocd/install/debian64/lib64:
==> default:
==> default: + bash /Host/Work/openocd/openocd.git/configure --prefix=/Host/Work/openocd/install/debian64/openocd --datarootdir=/Host/Work/openocd/install/debian64 --infodir=/Host/Work/openocd/install/debian64/openocd/info --localedir=/Host/Work/openocd/install/debian64/openocd/locale --mandir=/Host/Work/openocd/install/debian64/openocd/man --docdir=/Host/Work/openocd/install/debian64/openocd/doc --disable-wextra --disable-werror --enable-dependency-tracking '--enable-branding=GNU MCU Eclipse' --enable-aice --enable-amtjtagaccel --enable-armjtagew --enable-at91rm9200 --enable-bcm2835gpio --enable-buspirate --enable-cmsis-dap --enable-dummy --enable-ep93xx --enable-ftdi --enable-gw16012 --disable-ioutil --enable-jlink --enable-jtag_vpi --disable-minidriver-dummy --disable-oocd_trace --enable-opendous --enable-openjtag --enable-osbdm --enable-parport --disable-parport-ppdev --enable-parport-giveio --enable-presto --enable-remote-bitbang --enable-riscv --enable-rlink --enable-stlink --enable-sysfsgpio --enabl
==> default: e-ti-icdi --enable-ulink --enable-usb_blaster --enable-usb-blaster-2 --enable-usbprog --enable-vsllink --disable-zy1000-master --disable-zy1000
==> default: checking for makeinfo...
==> default: makeinfo
==> default: configure: error: cannot find install-sh, install.sh, or shtool in "/Host/Work/openocd/openocd.git" "/Host/Work/openocd/openocd.git/.." "/Host/Work/openocd/openocd.git/../.."

**Comment by ilg-ul** [comment]
there should be something terribly wrong, this looks like running inside the container, but it doesn't, since the container has all required tools.

do you see the script starting the bash inside the container?

**Comment by AntonKrug** [comment]
I'm running it inside Vagrant so I'm wondering if that could cause something to break.

**Comment by ilg-ul** [comment]
most probably.

**Comment by AntonKrug** [comment]
I think there might issue with vagrant that on Windows the stdin is not tty.

And for example you have the scripts:

do_host_build_target
or in the "preload-images" routines call the docker with --tty argument.

**Comment by ilg-ul** [comment]
> do_host_build_target

this should be used on only when running on macOS and targetting macOS. for all windows/linux the script should always run inside a Debian container.

I have no experience with vagrant, so I would suggest to run my script on a full Ubuntu 16, even virtual.

**Comment by AntonKrug** [comment]
What about run_docker_script, is using the --tty as well.

Vagrant is sitting on top of VirtualBox VM which helps with the orchestration of VMs, I think I should be able to start and use it directly from the VirtualBox.

**Comment by ilg-ul** [comment]
> directly from the VirtualBox.

yes, I think any virtual solution should work, as long as it it offers a full OS environment.

**Comment by AntonKrug** [comment]
I was doing to tear the VM down and start from scratch, but in the mean time I got something working which I was struggling for few days, so for the moment I will park this and will get back to you during the next week.

**Comment by ilg-ul** [comment]
ok

**Comment by AntonKrug** [comment]
The purge/reinstall from scratch might take longer than I expected. So in the mean time I removed the pkg-conf by hand and run the script from ssh and I was able to build win32 and debian32 binaries, so I will close this in the mean time and maybe reopen it later if the win64/debian64 might behave differently.

**Comment by ilg-ul** [comment]
> The purge/reinstall from scratch might take longer than I expected. 

when using virtual machines, I always take a snapshot right after the basic system is installed, and then copy/paste the entire folder to a separate templates folder.

when I need to create a new VM, I simply copy/paste the one from the templates and proceed from there.

if, for any reason, I manage to break the VM, it is easier to revert to the snapshot and proceed as from a clean install.

in both cases it is easier then reinstalling from scratch.

**Comment by AntonKrug** [comment]
Yes, that is one way to do it, probably I will have to fall back to it as well.
The other approach is to describe your VM environment with ruby and use Vagrant to always create the environment from scratch and to validate from time to time that the described dependencies are enough. And then have a repeatable process which can create the exact environment from nothing. With a VM snapshot in case of an issue, I can do "it works for me". With the Vagrant approach, I know what exact distro and packages and settings are required to get exact conditions as I have.

**Comment by ilg-ul** [comment]
> describe your VM environment with ruby and use Vagrant to always create the environment from scratch and to validate from time to time that the described dependencies are enough.

I never had enough patience to learn how to do this, so I cannot comment on it.

probably it may be ok for day to day work, but, if I understand it right, it does not _guarantee_ an imutable configuration, as Docker does by using read-only layers. in Docker you simply cannot write to an image, all writes are performed to a temporary layer on top of the image, layer that is disposed when the session is over. simple and efficient, perfect solution for release builds. for development builds, the solution I used was to perform the builds not on the internal ephemeral file system, but on a shared folder, so a broken build can be continued.

so, if you want to run my build scripts, I advise you to use the Docker configuration, preferably on a clean Ubuntu.

**Comment by AntonKrug** [comment]
Yes and No. You can configure to do both. 

Yes the files can be modified, that's why you have Vagrant on top which can completely destroy whole VM and completely start from empty image automatically every single time (if you want). Or you might configure it to be similar like LiveCD on every start. Or have a HDD which get destroyed and created every single time. I had the start from scratch every single time, before I applied some of the mods, now I actually want to stay in this state for a moment till I finish troubleshooting, then what I learn I can apply to the Vagrant scripts and then be able to teardown whole VM to start from scratch every time.

Exactly this is doing the Vagrant, gives you as a clean slate as you want.

**Comment by ilg-ul** [comment]
as you wish, but if you do not use the Docker images and need to customise the build script, you're on your own, I'm araid I cannot help you much.

**Comment by AntonKrug** [comment]
I use Docker images, but they need to run on some OS, and that OS is automated, so docker guarantees that their build is consistent and Vagrant can make even the OS on which the Docker runs consistent also.

Edit: You recommended to run the Docker on a specific Ubuntu version, so I generated the Vagrant files for exactly that Ubuntu.

**Pull request closed without merging**
